# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  auto_review:
    enabled: true
  review_instructions:
    - "Focus on logic errors, security vulnerabilities, and hallucinations."
    - "Ignore minor style/formatting issues (let Biome handle that)."
    - "Verify that server/client boundaries are respected (Convex backend functions vs React frontend)."
