import path from "node:path";
import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";

// Load environment variables from .env.local
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

/**
 * Playwright Configuration
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  // Test directory
  testDir: "./e2e",

  // Global setup/teardown
  globalSetup: "./e2e/global-setup.ts",
  globalTeardown: "./e2e/global-teardown.ts",

  // Run tests in parallel in ALL environments (CI and Local)
  fullyParallel: true,

  // Fail build on CI if test.only is left in code
  forbidOnly: !!process.env.CI,

  // Retries: 2 on CI only, no retries locally to catch flaky tests early
  retries: process.env.CI ? 2 : 0,

  // Restore to 4 workers as requested
  workers: 4,

  // Reporter configuration
  reporter: process.env.CI
    ? [["html", { open: "never" }], ["github"]]
    : [["html", { open: "on-failure" }]],

  // Global timeout for each test
  timeout: 60 * 1000,

  // Expect timeout for assertions
  expect: {
    timeout: 10 * 1000,
  },

  // Shared settings for all projects
  use: {
    // Base URL for navigation (use port 5555 to avoid conflicts with main dev server)
    baseURL: process.env.BASE_URL || "http://localhost:5555",

    // Trace on first retry (for debugging CI failures)
    trace: "on-first-retry",

    // Screenshot on failure only
    screenshot: "only-on-failure",

    // Video on first retry
    video: "on-first-retry",

    // Viewport size
    viewport: { width: 1280, height: 720 },

    // Ignore HTTPS errors (for local dev)
    ignoreHTTPSErrors: true,

    // Action timeout
    actionTimeout: 15 * 1000,

    // Navigation timeout
    navigationTimeout: 15 * 1000,
  },

  // Test projects for different browsers/scenarios
  projects: [
    // Desktop browsers
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    // Uncomment for cross-browser testing
    // {
    //   name: "firefox",
    //   use: { ...devices["Desktop Firefox"] },
    // },
    // {
    //   name: "webkit",
    //   use: { ...devices["Desktop Safari"] },
    // },

    // Mobile viewports
    // {
    //   name: "mobile-chrome",
    //   use: { ...devices["Pixel 5"] },
    // },
    // {
    //   name: "mobile-safari",
    //   use: { ...devices["iPhone 12"] },
    // },
  ],

  // Web server configuration
  // Starts BOTH frontend (Vite) AND backend (Convex) for E2E tests
  // In CI: use preview mode (pre-built dist/) for faster tests
  // Locally: use dev mode for hot reload
  webServer: {
    // In CI: Use existing build artifacts (generated by build job) to save time
    // Locally: use dev for speed
    command: process.env.CI ? "pnpm run preview" : "pnpm run dev",
    url: "http://127.0.0.1:5555",
    reuseExistingServer: !process.env.CI,
    timeout: 180 * 1000, // Increased timeout for build process
    // Wait for the React app to be fully loaded (not just port open)
    stdout: "ignore",
    stderr: "pipe",
  },

  // Output directories
  outputDir: "test-results",
});
