/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAppCompanySlugDashboardRouteImport } from './routes/_auth/_app/$companySlug/dashboard'
import { Route as AuthAppCompanySlugDocumentsIdRouteImport } from './routes/_auth/_app/$companySlug/documents/$id'
import { Route as AuthAppCompanySlugDocumentsIndexRouteImport } from './routes/_auth/_app/$companySlug/documents/index'
import { Route as AuthAppCompanySlugDocumentsTemplatesRouteImport } from './routes/_auth/_app/$companySlug/documents/templates'
import { Route as AuthAppCompanySlugIndexRouteImport } from './routes/_auth/_app/$companySlug/index'
import { Route as AuthAppCompanySlugIssuesKeyRouteImport } from './routes/_auth/_app/$companySlug/issues/$key'
import { Route as AuthAppCompanySlugProjectsKeyBoardRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/board'
import { Route as AuthAppCompanySlugProjectsKeyCalendarRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/calendar'
import { Route as AuthAppCompanySlugProjectsKeyIndexRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/index'
import { Route as AuthAppCompanySlugProjectsKeyRouteRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/route'
import { Route as AuthAppCompanySlugProjectsKeySettingsRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/settings'
import { Route as AuthAppCompanySlugProjectsKeyTimesheetRouteImport } from './routes/_auth/_app/$companySlug/projects/$key/timesheet'
import { Route as AuthAppCompanySlugProjectsIndexRouteImport } from './routes/_auth/_app/$companySlug/projects/index'
import { Route as AuthAppCompanySlugRouteRouteImport } from './routes/_auth/_app/$companySlug/route'
import { Route as AuthAppCompanySlugSettingsIndexRouteImport } from './routes/_auth/_app/$companySlug/settings/index'
import { Route as AuthAppCompanySlugSettingsProfileRouteImport } from './routes/_auth/_app/$companySlug/settings/profile'
import { Route as AuthAppCompanySlugTimeTrackingRouteImport } from './routes/_auth/_app/$companySlug/time-tracking'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/index'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/route'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/settings'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/index'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/index'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/route'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/index'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/route'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
import { Route as AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/index'
import { Route as AuthAppCompanySlugWorkspacesIndexRouteImport } from './routes/_auth/_app/$companySlug/workspaces/index'
import { Route as AuthAppAppRouteImport } from './routes/_auth/_app/app'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/_app/route'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppAppRoute = AuthAppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCompanySlugRouteRoute = AuthAppCompanySlugRouteRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCompanySlugIndexRoute = AuthAppCompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppCompanySlugRouteRoute,
} as any)
const AuthAppCompanySlugTimeTrackingRoute =
  AuthAppCompanySlugTimeTrackingRouteImport.update({
    id: '/time-tracking',
    path: '/time-tracking',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugDashboardRoute =
  AuthAppCompanySlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesIndexRoute =
  AuthAppCompanySlugWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugSettingsIndexRoute =
  AuthAppCompanySlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsIndexRoute =
  AuthAppCompanySlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugDocumentsIndexRoute =
  AuthAppCompanySlugDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugSettingsProfileRoute =
  AuthAppCompanySlugSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugIssuesKeyRoute =
  AuthAppCompanySlugIssuesKeyRouteImport.update({
    id: '/issues/$key',
    path: '/issues/$key',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugDocumentsTemplatesRoute =
  AuthAppCompanySlugDocumentsTemplatesRouteImport.update({
    id: '/documents/templates',
    path: '/documents/templates',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugDocumentsIdRoute =
  AuthAppCompanySlugDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeyRouteRoute =
  AuthAppCompanySlugProjectsKeyRouteRouteImport.update({
    id: '/projects/$key',
    path: '/projects/$key',
    getParentRoute: () => AuthAppCompanySlugRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeyIndexRoute =
  AuthAppCompanySlugProjectsKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAppCompanySlugProjectsKeyRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeyTimesheetRoute =
  AuthAppCompanySlugProjectsKeyTimesheetRouteImport.update({
    id: '/timesheet',
    path: '/timesheet',
    getParentRoute: () => AuthAppCompanySlugProjectsKeyRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeySettingsRoute =
  AuthAppCompanySlugProjectsKeySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthAppCompanySlugProjectsKeyRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeyCalendarRoute =
  AuthAppCompanySlugProjectsKeyCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthAppCompanySlugProjectsKeyRouteRoute,
  } as any)
const AuthAppCompanySlugProjectsKeyBoardRoute =
  AuthAppCompanySlugProjectsKeyBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthAppCompanySlugProjectsKeyRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteImport.update(
    {
      id: '/teams/$teamSlug',
      path: '/teams/$teamSlug',
      getParentRoute: () => AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRouteImport.update(
    {
      id: '/calendar',
      path: '/calendar',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRouteImport.update(
    {
      id: '/board',
      path: '/board',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRouteImport.update(
    {
      id: '/projects/',
      path: '/projects/',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteImport.update(
    {
      id: '/projects/$key',
      path: '/projects/$key',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRouteImport.update(
    {
      id: '/timesheet',
      path: '/timesheet',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRouteImport.update(
    {
      id: '/calendar',
      path: '/calendar',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute,
    } as any,
  )
const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRouteImport.update(
    {
      id: '/board',
      path: '/board',
      getParentRoute: () =>
        AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$companySlug': typeof AuthAppCompanySlugRouteRouteWithChildren
  '/app': typeof AuthAppAppRoute
  '/$companySlug/dashboard': typeof AuthAppCompanySlugDashboardRoute
  '/$companySlug/time-tracking': typeof AuthAppCompanySlugTimeTrackingRoute
  '/$companySlug/': typeof AuthAppCompanySlugIndexRoute
  '/$companySlug/projects/$key': typeof AuthAppCompanySlugProjectsKeyRouteRouteWithChildren
  '/$companySlug/workspaces/$workspaceSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/$companySlug/documents/$id': typeof AuthAppCompanySlugDocumentsIdRoute
  '/$companySlug/documents/templates': typeof AuthAppCompanySlugDocumentsTemplatesRoute
  '/$companySlug/issues/$key': typeof AuthAppCompanySlugIssuesKeyRoute
  '/$companySlug/settings/profile': typeof AuthAppCompanySlugSettingsProfileRoute
  '/$companySlug/documents': typeof AuthAppCompanySlugDocumentsIndexRoute
  '/$companySlug/projects': typeof AuthAppCompanySlugProjectsIndexRoute
  '/$companySlug/settings': typeof AuthAppCompanySlugSettingsIndexRoute
  '/$companySlug/workspaces': typeof AuthAppCompanySlugWorkspacesIndexRoute
  '/$companySlug/projects/$key/board': typeof AuthAppCompanySlugProjectsKeyBoardRoute
  '/$companySlug/projects/$key/calendar': typeof AuthAppCompanySlugProjectsKeyCalendarRoute
  '/$companySlug/projects/$key/settings': typeof AuthAppCompanySlugProjectsKeySettingsRoute
  '/$companySlug/projects/$key/timesheet': typeof AuthAppCompanySlugProjectsKeyTimesheetRoute
  '/$companySlug/workspaces/$workspaceSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute
  '/$companySlug/projects/$key/': typeof AuthAppCompanySlugProjectsKeyIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteWithChildren
  '/$companySlug/workspaces/$workspaceSlug/teams': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteWithChildren
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AuthAppAppRoute
  '/$companySlug/dashboard': typeof AuthAppCompanySlugDashboardRoute
  '/$companySlug/time-tracking': typeof AuthAppCompanySlugTimeTrackingRoute
  '/$companySlug': typeof AuthAppCompanySlugIndexRoute
  '/$companySlug/documents/$id': typeof AuthAppCompanySlugDocumentsIdRoute
  '/$companySlug/documents/templates': typeof AuthAppCompanySlugDocumentsTemplatesRoute
  '/$companySlug/issues/$key': typeof AuthAppCompanySlugIssuesKeyRoute
  '/$companySlug/settings/profile': typeof AuthAppCompanySlugSettingsProfileRoute
  '/$companySlug/documents': typeof AuthAppCompanySlugDocumentsIndexRoute
  '/$companySlug/projects': typeof AuthAppCompanySlugProjectsIndexRoute
  '/$companySlug/settings': typeof AuthAppCompanySlugSettingsIndexRoute
  '/$companySlug/workspaces': typeof AuthAppCompanySlugWorkspacesIndexRoute
  '/$companySlug/projects/$key/board': typeof AuthAppCompanySlugProjectsKeyBoardRoute
  '/$companySlug/projects/$key/calendar': typeof AuthAppCompanySlugProjectsKeyCalendarRoute
  '/$companySlug/projects/$key/settings': typeof AuthAppCompanySlugProjectsKeySettingsRoute
  '/$companySlug/projects/$key/timesheet': typeof AuthAppCompanySlugProjectsKeyTimesheetRoute
  '/$companySlug/workspaces/$workspaceSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute
  '/$companySlug/projects/$key': typeof AuthAppCompanySlugProjectsKeyIndexRoute
  '/$companySlug/workspaces/$workspaceSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute
  '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_auth/_app': typeof AuthAppRouteRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_auth/_app/$companySlug': typeof AuthAppCompanySlugRouteRouteWithChildren
  '/_auth/_app/app': typeof AuthAppAppRoute
  '/_auth/_app/$companySlug/dashboard': typeof AuthAppCompanySlugDashboardRoute
  '/_auth/_app/$companySlug/time-tracking': typeof AuthAppCompanySlugTimeTrackingRoute
  '/_auth/_app/$companySlug/': typeof AuthAppCompanySlugIndexRoute
  '/_auth/_app/$companySlug/projects/$key': typeof AuthAppCompanySlugProjectsKeyRouteRouteWithChildren
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/_auth/_app/$companySlug/documents/$id': typeof AuthAppCompanySlugDocumentsIdRoute
  '/_auth/_app/$companySlug/documents/templates': typeof AuthAppCompanySlugDocumentsTemplatesRoute
  '/_auth/_app/$companySlug/issues/$key': typeof AuthAppCompanySlugIssuesKeyRoute
  '/_auth/_app/$companySlug/settings/profile': typeof AuthAppCompanySlugSettingsProfileRoute
  '/_auth/_app/$companySlug/documents/': typeof AuthAppCompanySlugDocumentsIndexRoute
  '/_auth/_app/$companySlug/projects/': typeof AuthAppCompanySlugProjectsIndexRoute
  '/_auth/_app/$companySlug/settings/': typeof AuthAppCompanySlugSettingsIndexRoute
  '/_auth/_app/$companySlug/workspaces/': typeof AuthAppCompanySlugWorkspacesIndexRoute
  '/_auth/_app/$companySlug/projects/$key/board': typeof AuthAppCompanySlugProjectsKeyBoardRoute
  '/_auth/_app/$companySlug/projects/$key/calendar': typeof AuthAppCompanySlugProjectsKeyCalendarRoute
  '/_auth/_app/$companySlug/projects/$key/settings': typeof AuthAppCompanySlugProjectsKeySettingsRoute
  '/_auth/_app/$companySlug/projects/$key/timesheet': typeof AuthAppCompanySlugProjectsKeyTimesheetRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute
  '/_auth/_app/$companySlug/projects/$key/': typeof AuthAppCompanySlugProjectsKeyIndexRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteWithChildren
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteWithChildren
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute
  '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/': typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/onboarding'
    | '/invite/$token'
    | '/$companySlug'
    | '/app'
    | '/$companySlug/dashboard'
    | '/$companySlug/time-tracking'
    | '/$companySlug/'
    | '/$companySlug/projects/$key'
    | '/$companySlug/workspaces/$workspaceSlug'
    | '/$companySlug/documents/$id'
    | '/$companySlug/documents/templates'
    | '/$companySlug/issues/$key'
    | '/$companySlug/settings/profile'
    | '/$companySlug/documents'
    | '/$companySlug/projects'
    | '/$companySlug/settings'
    | '/$companySlug/workspaces'
    | '/$companySlug/projects/$key/board'
    | '/$companySlug/projects/$key/calendar'
    | '/$companySlug/projects/$key/settings'
    | '/$companySlug/projects/$key/timesheet'
    | '/$companySlug/workspaces/$workspaceSlug/settings'
    | '/$companySlug/projects/$key/'
    | '/$companySlug/workspaces/$workspaceSlug/'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug'
    | '/$companySlug/workspaces/$workspaceSlug/teams'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/onboarding'
    | '/invite/$token'
    | '/app'
    | '/$companySlug/dashboard'
    | '/$companySlug/time-tracking'
    | '/$companySlug'
    | '/$companySlug/documents/$id'
    | '/$companySlug/documents/templates'
    | '/$companySlug/issues/$key'
    | '/$companySlug/settings/profile'
    | '/$companySlug/documents'
    | '/$companySlug/projects'
    | '/$companySlug/settings'
    | '/$companySlug/workspaces'
    | '/$companySlug/projects/$key/board'
    | '/$companySlug/projects/$key/calendar'
    | '/$companySlug/projects/$key/settings'
    | '/$companySlug/projects/$key/timesheet'
    | '/$companySlug/workspaces/$workspaceSlug/settings'
    | '/$companySlug/projects/$key'
    | '/$companySlug/workspaces/$workspaceSlug'
    | '/$companySlug/workspaces/$workspaceSlug/teams'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
    | '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/_auth/_app'
    | '/_auth/onboarding'
    | '/invite/$token'
    | '/_auth/_app/$companySlug'
    | '/_auth/_app/app'
    | '/_auth/_app/$companySlug/dashboard'
    | '/_auth/_app/$companySlug/time-tracking'
    | '/_auth/_app/$companySlug/'
    | '/_auth/_app/$companySlug/projects/$key'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug'
    | '/_auth/_app/$companySlug/documents/$id'
    | '/_auth/_app/$companySlug/documents/templates'
    | '/_auth/_app/$companySlug/issues/$key'
    | '/_auth/_app/$companySlug/settings/profile'
    | '/_auth/_app/$companySlug/documents/'
    | '/_auth/_app/$companySlug/projects/'
    | '/_auth/_app/$companySlug/settings/'
    | '/_auth/_app/$companySlug/workspaces/'
    | '/_auth/_app/$companySlug/projects/$key/board'
    | '/_auth/_app/$companySlug/projects/$key/calendar'
    | '/_auth/_app/$companySlug/projects/$key/settings'
    | '/_auth/_app/$companySlug/projects/$key/timesheet'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/settings'
    | '/_auth/_app/$companySlug/projects/$key/'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
    | '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_app': {
      id: '/_auth/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_app/app': {
      id: '/_auth/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppAppRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/_app/$companySlug': {
      id: '/_auth/_app/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof AuthAppCompanySlugRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/_app/$companySlug/': {
      id: '/_auth/_app/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthAppCompanySlugIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/time-tracking': {
      id: '/_auth/_app/$companySlug/time-tracking'
      path: '/time-tracking'
      fullPath: '/$companySlug/time-tracking'
      preLoaderRoute: typeof AuthAppCompanySlugTimeTrackingRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/dashboard': {
      id: '/_auth/_app/$companySlug/dashboard'
      path: '/dashboard'
      fullPath: '/$companySlug/dashboard'
      preLoaderRoute: typeof AuthAppCompanySlugDashboardRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/': {
      id: '/_auth/_app/$companySlug/workspaces/'
      path: '/workspaces'
      fullPath: '/$companySlug/workspaces'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/settings/': {
      id: '/_auth/_app/$companySlug/settings/'
      path: '/settings'
      fullPath: '/$companySlug/settings'
      preLoaderRoute: typeof AuthAppCompanySlugSettingsIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/projects/': {
      id: '/_auth/_app/$companySlug/projects/'
      path: '/projects'
      fullPath: '/$companySlug/projects'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/documents/': {
      id: '/_auth/_app/$companySlug/documents/'
      path: '/documents'
      fullPath: '/$companySlug/documents'
      preLoaderRoute: typeof AuthAppCompanySlugDocumentsIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/settings/profile': {
      id: '/_auth/_app/$companySlug/settings/profile'
      path: '/settings/profile'
      fullPath: '/$companySlug/settings/profile'
      preLoaderRoute: typeof AuthAppCompanySlugSettingsProfileRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/issues/$key': {
      id: '/_auth/_app/$companySlug/issues/$key'
      path: '/issues/$key'
      fullPath: '/$companySlug/issues/$key'
      preLoaderRoute: typeof AuthAppCompanySlugIssuesKeyRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/documents/templates': {
      id: '/_auth/_app/$companySlug/documents/templates'
      path: '/documents/templates'
      fullPath: '/$companySlug/documents/templates'
      preLoaderRoute: typeof AuthAppCompanySlugDocumentsTemplatesRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/documents/$id': {
      id: '/_auth/_app/$companySlug/documents/$id'
      path: '/documents/$id'
      fullPath: '/$companySlug/documents/$id'
      preLoaderRoute: typeof AuthAppCompanySlugDocumentsIdRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/$companySlug/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key': {
      id: '/_auth/_app/$companySlug/projects/$key'
      path: '/projects/$key'
      fullPath: '/$companySlug/projects/$key'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeyRouteRouteImport
      parentRoute: typeof AuthAppCompanySlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key/': {
      id: '/_auth/_app/$companySlug/projects/$key/'
      path: '/'
      fullPath: '/$companySlug/projects/$key/'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeyIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/settings': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key/timesheet': {
      id: '/_auth/_app/$companySlug/projects/$key/timesheet'
      path: '/timesheet'
      fullPath: '/$companySlug/projects/$key/timesheet'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeyTimesheetRouteImport
      parentRoute: typeof AuthAppCompanySlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key/settings': {
      id: '/_auth/_app/$companySlug/projects/$key/settings'
      path: '/settings'
      fullPath: '/$companySlug/projects/$key/settings'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeySettingsRouteImport
      parentRoute: typeof AuthAppCompanySlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key/calendar': {
      id: '/_auth/_app/$companySlug/projects/$key/calendar'
      path: '/calendar'
      fullPath: '/$companySlug/projects/$key/calendar'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeyCalendarRouteImport
      parentRoute: typeof AuthAppCompanySlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/projects/$key/board': {
      id: '/_auth/_app/$companySlug/projects/$key/board'
      path: '/board'
      fullPath: '/$companySlug/projects/$key/board'
      preLoaderRoute: typeof AuthAppCompanySlugProjectsKeyBoardRouteImport
      parentRoute: typeof AuthAppCompanySlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/'
      path: '/teams'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug'
      path: '/teams/$teamSlug'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/'
      path: '/'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
      path: '/settings'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/settings'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
      path: '/calendar'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/calendar'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
      path: '/board'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/board'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/'
      path: '/projects'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key'
      path: '/projects/$key'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/'
      path: '/'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
      path: '/timesheet'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/timesheet'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
      path: '/settings'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/settings'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
      path: '/calendar'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/calendar'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute
    }
    '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board': {
      id: '/_auth/_app/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
      path: '/board'
      fullPath: '/$companySlug/workspaces/$workspaceSlug/teams/$teamSlug/projects/$key/board'
      preLoaderRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRouteImport
      parentRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute
    }
  }
}

interface AuthAppCompanySlugProjectsKeyRouteRouteChildren {
  AuthAppCompanySlugProjectsKeyBoardRoute: typeof AuthAppCompanySlugProjectsKeyBoardRoute
  AuthAppCompanySlugProjectsKeyCalendarRoute: typeof AuthAppCompanySlugProjectsKeyCalendarRoute
  AuthAppCompanySlugProjectsKeySettingsRoute: typeof AuthAppCompanySlugProjectsKeySettingsRoute
  AuthAppCompanySlugProjectsKeyTimesheetRoute: typeof AuthAppCompanySlugProjectsKeyTimesheetRoute
  AuthAppCompanySlugProjectsKeyIndexRoute: typeof AuthAppCompanySlugProjectsKeyIndexRoute
}

const AuthAppCompanySlugProjectsKeyRouteRouteChildren: AuthAppCompanySlugProjectsKeyRouteRouteChildren =
  {
    AuthAppCompanySlugProjectsKeyBoardRoute:
      AuthAppCompanySlugProjectsKeyBoardRoute,
    AuthAppCompanySlugProjectsKeyCalendarRoute:
      AuthAppCompanySlugProjectsKeyCalendarRoute,
    AuthAppCompanySlugProjectsKeySettingsRoute:
      AuthAppCompanySlugProjectsKeySettingsRoute,
    AuthAppCompanySlugProjectsKeyTimesheetRoute:
      AuthAppCompanySlugProjectsKeyTimesheetRoute,
    AuthAppCompanySlugProjectsKeyIndexRoute:
      AuthAppCompanySlugProjectsKeyIndexRoute,
  }

const AuthAppCompanySlugProjectsKeyRouteRouteWithChildren =
  AuthAppCompanySlugProjectsKeyRouteRoute._addFileChildren(
    AuthAppCompanySlugProjectsKeyRouteRouteChildren,
  )

interface AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteChildren {
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute
}

const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteChildren: AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteChildren =
  {
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyBoardRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyCalendarRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeySettingsRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyTimesheetRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyIndexRoute,
  }

const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteWithChildren =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute._addFileChildren(
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteChildren,
  )

interface AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteChildren {
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteWithChildren
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute
}

const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteChildren: AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteChildren =
  {
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugBoardRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugCalendarRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugSettingsRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugIndexRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsKeyRouteRouteWithChildren,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugProjectsIndexRoute,
  }

const AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteWithChildren =
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute._addFileChildren(
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteChildren,
  )

interface AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteChildren {
  AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteWithChildren
  AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute
}

const AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteChildren: AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteChildren =
  {
    AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugSettingsRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugIndexRoute,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsTeamSlugRouteRouteWithChildren,
    AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugTeamsIndexRoute,
  }

const AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteWithChildren =
  AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute._addFileChildren(
    AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteChildren,
  )

interface AuthAppCompanySlugRouteRouteChildren {
  AuthAppCompanySlugDashboardRoute: typeof AuthAppCompanySlugDashboardRoute
  AuthAppCompanySlugTimeTrackingRoute: typeof AuthAppCompanySlugTimeTrackingRoute
  AuthAppCompanySlugIndexRoute: typeof AuthAppCompanySlugIndexRoute
  AuthAppCompanySlugProjectsKeyRouteRoute: typeof AuthAppCompanySlugProjectsKeyRouteRouteWithChildren
  AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute: typeof AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteWithChildren
  AuthAppCompanySlugDocumentsIdRoute: typeof AuthAppCompanySlugDocumentsIdRoute
  AuthAppCompanySlugDocumentsTemplatesRoute: typeof AuthAppCompanySlugDocumentsTemplatesRoute
  AuthAppCompanySlugIssuesKeyRoute: typeof AuthAppCompanySlugIssuesKeyRoute
  AuthAppCompanySlugSettingsProfileRoute: typeof AuthAppCompanySlugSettingsProfileRoute
  AuthAppCompanySlugDocumentsIndexRoute: typeof AuthAppCompanySlugDocumentsIndexRoute
  AuthAppCompanySlugProjectsIndexRoute: typeof AuthAppCompanySlugProjectsIndexRoute
  AuthAppCompanySlugSettingsIndexRoute: typeof AuthAppCompanySlugSettingsIndexRoute
  AuthAppCompanySlugWorkspacesIndexRoute: typeof AuthAppCompanySlugWorkspacesIndexRoute
}

const AuthAppCompanySlugRouteRouteChildren: AuthAppCompanySlugRouteRouteChildren =
  {
    AuthAppCompanySlugDashboardRoute: AuthAppCompanySlugDashboardRoute,
    AuthAppCompanySlugTimeTrackingRoute: AuthAppCompanySlugTimeTrackingRoute,
    AuthAppCompanySlugIndexRoute: AuthAppCompanySlugIndexRoute,
    AuthAppCompanySlugProjectsKeyRouteRoute:
      AuthAppCompanySlugProjectsKeyRouteRouteWithChildren,
    AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRoute:
      AuthAppCompanySlugWorkspacesWorkspaceSlugRouteRouteWithChildren,
    AuthAppCompanySlugDocumentsIdRoute: AuthAppCompanySlugDocumentsIdRoute,
    AuthAppCompanySlugDocumentsTemplatesRoute:
      AuthAppCompanySlugDocumentsTemplatesRoute,
    AuthAppCompanySlugIssuesKeyRoute: AuthAppCompanySlugIssuesKeyRoute,
    AuthAppCompanySlugSettingsProfileRoute:
      AuthAppCompanySlugSettingsProfileRoute,
    AuthAppCompanySlugDocumentsIndexRoute:
      AuthAppCompanySlugDocumentsIndexRoute,
    AuthAppCompanySlugProjectsIndexRoute: AuthAppCompanySlugProjectsIndexRoute,
    AuthAppCompanySlugSettingsIndexRoute: AuthAppCompanySlugSettingsIndexRoute,
    AuthAppCompanySlugWorkspacesIndexRoute:
      AuthAppCompanySlugWorkspacesIndexRoute,
  }

const AuthAppCompanySlugRouteRouteWithChildren =
  AuthAppCompanySlugRouteRoute._addFileChildren(
    AuthAppCompanySlugRouteRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppCompanySlugRouteRoute: typeof AuthAppCompanySlugRouteRouteWithChildren
  AuthAppAppRoute: typeof AuthAppAppRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppCompanySlugRouteRoute: AuthAppCompanySlugRouteRouteWithChildren,
  AuthAppAppRoute: AuthAppAppRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
