/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppIssuesKeyRouteImport } from './routes/_app/issues/$key'
import { Route as AppDocumentsIdRouteImport } from './routes/_app/documents/$id'
import { Route as AppProjectsKeyRouteRouteImport } from './routes/_app/projects/$key/route'
import { Route as AppProjectsKeyIndexRouteImport } from './routes/_app/projects/$key/index'
import { Route as AppProjectsKeyTimesheetRouteImport } from './routes/_app/projects/$key/timesheet'
import { Route as AppProjectsKeySettingsRouteImport } from './routes/_app/projects/$key/settings'
import { Route as AppProjectsKeyCalendarRouteImport } from './routes/_app/projects/$key/calendar'
import { Route as AppProjectsKeyBoardRouteImport } from './routes/_app/projects/$key/board'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIssuesKeyRoute = AppIssuesKeyRouteImport.update({
  id: '/issues/$key',
  path: '/issues/$key',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsKeyRouteRoute = AppProjectsKeyRouteRouteImport.update({
  id: '/projects/$key',
  path: '/projects/$key',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsKeyIndexRoute = AppProjectsKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsKeyRouteRoute,
} as any)
const AppProjectsKeyTimesheetRoute = AppProjectsKeyTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppProjectsKeyRouteRoute,
} as any)
const AppProjectsKeySettingsRoute = AppProjectsKeySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsKeyRouteRoute,
} as any)
const AppProjectsKeyCalendarRoute = AppProjectsKeyCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppProjectsKeyRouteRoute,
} as any)
const AppProjectsKeyBoardRoute = AppProjectsKeyBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppProjectsKeyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$key': typeof AppProjectsKeyRouteRouteWithChildren
  '/documents/$id': typeof AppDocumentsIdRoute
  '/issues/$key': typeof AppIssuesKeyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$key/board': typeof AppProjectsKeyBoardRoute
  '/projects/$key/calendar': typeof AppProjectsKeyCalendarRoute
  '/projects/$key/settings': typeof AppProjectsKeySettingsRoute
  '/projects/$key/timesheet': typeof AppProjectsKeyTimesheetRoute
  '/projects/$key/': typeof AppProjectsKeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/issues/$key': typeof AppIssuesKeyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/projects/$key/board': typeof AppProjectsKeyBoardRoute
  '/projects/$key/calendar': typeof AppProjectsKeyCalendarRoute
  '/projects/$key/settings': typeof AppProjectsKeySettingsRoute
  '/projects/$key/timesheet': typeof AppProjectsKeyTimesheetRoute
  '/projects/$key': typeof AppProjectsKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/projects/$key': typeof AppProjectsKeyRouteRouteWithChildren
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/issues/$key': typeof AppIssuesKeyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/projects/$key/board': typeof AppProjectsKeyBoardRoute
  '/_app/projects/$key/calendar': typeof AppProjectsKeyCalendarRoute
  '/_app/projects/$key/settings': typeof AppProjectsKeySettingsRoute
  '/_app/projects/$key/timesheet': typeof AppProjectsKeyTimesheetRoute
  '/_app/projects/$key/': typeof AppProjectsKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/invite/$token'
    | '/projects/$key'
    | '/documents/$id'
    | '/issues/$key'
    | '/settings/profile'
    | '/documents'
    | '/projects'
    | '/settings'
    | '/projects/$key/board'
    | '/projects/$key/calendar'
    | '/projects/$key/settings'
    | '/projects/$key/timesheet'
    | '/projects/$key/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/invite/$token'
    | '/documents/$id'
    | '/issues/$key'
    | '/settings/profile'
    | '/documents'
    | '/projects'
    | '/settings'
    | '/projects/$key/board'
    | '/projects/$key/calendar'
    | '/projects/$key/settings'
    | '/projects/$key/timesheet'
    | '/projects/$key'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/dashboard'
    | '/invite/$token'
    | '/_app/projects/$key'
    | '/_app/documents/$id'
    | '/_app/issues/$key'
    | '/_app/settings/profile'
    | '/_app/documents/'
    | '/_app/projects/'
    | '/_app/settings/'
    | '/_app/projects/$key/board'
    | '/_app/projects/$key/calendar'
    | '/_app/projects/$key/settings'
    | '/_app/projects/$key/timesheet'
    | '/_app/projects/$key/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/issues/$key': {
      id: '/_app/issues/$key'
      path: '/issues/$key'
      fullPath: '/issues/$key'
      preLoaderRoute: typeof AppIssuesKeyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$key': {
      id: '/_app/projects/$key'
      path: '/projects/$key'
      fullPath: '/projects/$key'
      preLoaderRoute: typeof AppProjectsKeyRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$key/': {
      id: '/_app/projects/$key/'
      path: '/'
      fullPath: '/projects/$key/'
      preLoaderRoute: typeof AppProjectsKeyIndexRouteImport
      parentRoute: typeof AppProjectsKeyRouteRoute
    }
    '/_app/projects/$key/timesheet': {
      id: '/_app/projects/$key/timesheet'
      path: '/timesheet'
      fullPath: '/projects/$key/timesheet'
      preLoaderRoute: typeof AppProjectsKeyTimesheetRouteImport
      parentRoute: typeof AppProjectsKeyRouteRoute
    }
    '/_app/projects/$key/settings': {
      id: '/_app/projects/$key/settings'
      path: '/settings'
      fullPath: '/projects/$key/settings'
      preLoaderRoute: typeof AppProjectsKeySettingsRouteImport
      parentRoute: typeof AppProjectsKeyRouteRoute
    }
    '/_app/projects/$key/calendar': {
      id: '/_app/projects/$key/calendar'
      path: '/calendar'
      fullPath: '/projects/$key/calendar'
      preLoaderRoute: typeof AppProjectsKeyCalendarRouteImport
      parentRoute: typeof AppProjectsKeyRouteRoute
    }
    '/_app/projects/$key/board': {
      id: '/_app/projects/$key/board'
      path: '/board'
      fullPath: '/projects/$key/board'
      preLoaderRoute: typeof AppProjectsKeyBoardRouteImport
      parentRoute: typeof AppProjectsKeyRouteRoute
    }
  }
}

interface AppProjectsKeyRouteRouteChildren {
  AppProjectsKeyBoardRoute: typeof AppProjectsKeyBoardRoute
  AppProjectsKeyCalendarRoute: typeof AppProjectsKeyCalendarRoute
  AppProjectsKeySettingsRoute: typeof AppProjectsKeySettingsRoute
  AppProjectsKeyTimesheetRoute: typeof AppProjectsKeyTimesheetRoute
  AppProjectsKeyIndexRoute: typeof AppProjectsKeyIndexRoute
}

const AppProjectsKeyRouteRouteChildren: AppProjectsKeyRouteRouteChildren = {
  AppProjectsKeyBoardRoute: AppProjectsKeyBoardRoute,
  AppProjectsKeyCalendarRoute: AppProjectsKeyCalendarRoute,
  AppProjectsKeySettingsRoute: AppProjectsKeySettingsRoute,
  AppProjectsKeyTimesheetRoute: AppProjectsKeyTimesheetRoute,
  AppProjectsKeyIndexRoute: AppProjectsKeyIndexRoute,
}

const AppProjectsKeyRouteRouteWithChildren =
  AppProjectsKeyRouteRoute._addFileChildren(AppProjectsKeyRouteRouteChildren)

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProjectsKeyRouteRoute: typeof AppProjectsKeyRouteRouteWithChildren
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
  AppIssuesKeyRoute: typeof AppIssuesKeyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProjectsKeyRouteRoute: AppProjectsKeyRouteRouteWithChildren,
  AppDocumentsIdRoute: AppDocumentsIdRoute,
  AppIssuesKeyRoute: AppIssuesKeyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
